# Schema for the views plugins of the REST export nested module.

views.display.rest_export_nested:
  type: views_display_path
  label: 'REST export  nested display options'
  mapping:
    auth:
      type: sequence
      label: 'Authentication'
      sequence:
        type: string
        label: 'Authentication Provider'
